# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [29]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import json
import gmaps
import os

# Import API key
from api_keys import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [30]:
csvpath = '../WeatherPy/output_data/cities.csv'
cities_df = pd.read_csv(csvpath, index_col=0)
cities_df

,City,Latitude,Longitude,Max Temperature (°C),Humidity (%),Cloudiness (%),Wind Speed (MPH),Country,Date
0,buala,-8.1450,159.5921,27.57,77,100,3.26,SB,1612411989
1,ushuaia,-54.8000,-68.3000,9.00,87,75,1.54,AR,1612411884
2,faanui,-16.4833,-151.7500,25.69,78,99,4.49,PF,1612411991
3,mataura,-46.1927,168.8643,17.96,38,0,3.79,NZ,1612411992
4,barrow,71.2906,-156.7887,-34.00,85,1,5.66,US,1612411968
...,...,...,...,...,...,...,...,...,...
562,qui nhon,13.7667,109.2333,23.56,81,95,7.52,VN,1612412675
563,kemijarvi,66.7131,27.4306,-6.30,96,100,5.37,FI,1612412676
564,ust-kut,56.7938,105.7672,-8.37,93,100,5.67,RU,1612412677
565,skoghall,59.3232,13.4655,-11.00,85,75,5.14,SE,1612412679
566,miles city,46.4083,-105.8406,-8.00,73,90,4.63,US,1612412630

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [31]:
locations = cities_df[["Latitude", "Longitude"]]
humidity = cities_df['Humidity (%)'].astype(float)

# Plot Heatmap
fig = gmaps.figure()

# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, 
                                 dissipating=False, max_intensity=100,
                                 point_radius=1)

# Add layer
fig.add_layer(heat_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [37]:
ideal_cities_df = cities_df.loc[(cities_df['Max Temperature (°C)'] > 21.11) &
                        (cities_df['Max Temperature (°C)'] < 26.67) & 
                        (cities_df['Wind Speed (MPH)'] < 10) &
                        (cities_df['Cloudiness (%)'] == 0)
                       ]
hotel_df = ideal_cities_df.dropna()
print(f'There are {len(hotel_df)} ideal cities for vacation')
hotel_df

There are 17 ideal cities for vacation

,City,Latitude,Longitude,Max Temperature (°C),Humidity (%),Cloudiness (%),Wind Speed (MPH),Country,Date
15,rikitea,-23.1203,-134.9692,25.59,71,0,5.66,PF,1612412006
34,kankon,15.0167,74.0167,25.00,53,0,3.09,IN,1612412029
46,pisco,-13.7000,-76.2167,21.67,88,0,1.03,PE,1612412044
136,victoria,22.2855,114.1577,24.00,35,0,4.63,HK,1612412161
139,busselton,-33.6500,115.3333,22.78,42,0,1.34,AU,1612412138
149,bonthe,7.5264,-12.5050,24.95,86,0,2.01,SL,1612412176
174,sur,22.5667,59.5289,21.89,58,0,2.51,OM,1612412206
267,maceio,-9.6658,-35.7353,23.00,94,0,0.51,BR,1612412318
268,tura,25.5198,90.2201,24.09,38,0,0.19,IN,1612412319
326,touros,-5.1989,-35.4608,25.00,83,0,3.09,BR,1612412388
328,cape coast,5.1053,-1.2466,26.39,87,0,3.14,GH,1612412101
397,mumford,5.2618,-0.7590,26.37,87,0,3.72,GH,1612412478
425,vila velha,-20.3297,-40.2925,25.00,83,0,2.57,BR,1612412285
476,veraval,20.9000,70.3667,22.11,56,0,5.37,IN,1612412575
480,mae hong son,19.3003,97.9685,24.00,50,0,1.03,TH,1612412579
486,sao joao da barra,-21.6403,-41.0511,24.97,85,0,7.52,BR,1612412586
531,lagoa santa,-19.6272,-43.8897,24.00,68,0,1.03,BR,1612412637

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [38]:
# geocoordinates
Latitude = hotel_df['Latitude'].tolist()
Longitude = hotel_df['Longitude'].tolist()
hotel_lst = []

for i in range(len(hotel_df)):
    target_coordinates = f"{Latitude[i]}, {Longitude[i]}"
    target_search = "hotel"
    target_radius = 5000
    target_type = "hotel"

    # set up a parameters dictionary
    params = {
        "location": target_coordinates,
        "keyword": target_search,
        "radius": target_radius,
        "type": target_type,
        "key": g_key
    }
    
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # run a request using our params dictionary
    response = requests.get(base_url, params=params).json()
    hotel_lst.append(response['results'][0]['name'])
    
hotel_df['Hotel Name'] = hotel_lst

In [39]:
hotel_df

,City,Latitude,Longitude,Max Temperature (°C),Humidity (%),Cloudiness (%),Wind Speed (MPH),Country,Date,Hotel Name
15,rikitea,-23.1203,-134.9692,25.59,71,0,5.66,PF,1612412006,Pension Bianca & Benoit
34,kankon,15.0167,74.0167,25.00,53,0,3.09,IN,1612412029,THE WHITE
46,pisco,-13.7000,-76.2167,21.67,88,0,1.03,PE,1612412044,HOSTAL MIRAMAR
136,victoria,22.2855,114.1577,24.00,35,0,4.63,HK,1612412161,The OTTO Hotel
139,busselton,-33.6500,115.3333,22.78,42,0,1.34,AU,1612412138,The Sebel Busselton
149,bonthe,7.5264,-12.5050,24.95,86,0,2.01,SL,1612412176,Bonthe Holiday Village
174,sur,22.5667,59.5289,21.89,58,0,2.51,OM,1612412206,Sur Plaza Hotel
267,maceio,-9.6658,-35.7353,23.00,94,0,0.51,BR,1612412318,Acqua Suítes
268,tura,25.5198,90.2201,24.09,38,0,0.19,IN,1612412319,"Dongrama Home Stay, Tura Meghalaya"
326,touros,-5.1989,-35.4608,25.00,83,0,3.09,BR,1612412388,Hotel Vila Gale Touros
328,cape coast,5.1053,-1.2466,26.39,87,0,3.14,GH,1612412101,"Ridge Royal Hotel, Cape Coast Ghana"
397,mumford,5.2618,-0.7590,26.37,87,0,3.72,GH,1612412478,Blue Diamond Beach and Spa Resort
425,vila velha,-20.3297,-40.2925,25.00,83,0,2.57,BR,1612412285,Golden Tulip Porto Vitória
476,veraval,20.9000,70.3667,22.11,56,0,5.37,IN,1612412575,HOTEL PLATINUM
480,mae hong son,19.3003,97.9685,24.00,50,0,1.03,TH,1612412579,Imperial Mae Hong Son Hotel
486,sao joao da barra,-21.6403,-41.0511,24.97,85,0,7.52,BR,1612412586,OYO Pousada Mediterrâneo
531,lagoa santa,-19.6272,-43.8897,24.00,68,0,1.03,BR,1612412637,Ramada by Wyndham Lagoa Santa INTL Airport Bel...

In [46]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Latitude", "Longitude"]]

In [47]:
# Add marker layer ontop of heat map
coordinates = [(Latitude[i], Longitude[i]) for i in range(len(Latitude))]
coordinates

markers = gmaps.marker_layer(coordinates)

# Display figure
fig.add_layer(markers)
fig

Figure(layout=FigureLayout(height='420px'))